# Generated by Django 5.2.3 on 2025-08-07 02:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id_address', primary_key=True, serialize=False)),
                ('address_complete', models.TextField(help_text='Dirección exacta y completa (calle, casa, etc.)')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'data_locations"."addresses',
            },
        ),
        migrations.CreateModel(
            name='AuthSecurity',
            fields=[
                ('id', models.BigAutoField(db_column='id_auth', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si un usuario se encuentra activo.')),
                ('is_blocked', models.BooleanField(default=False, help_text='Indica si un usuario se encuentra bloqueado.')),
                ('verification_code', models.CharField(blank=True, help_text='Código de verificación, ej: para olvido de clave.', max_length=10, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, help_text='Última fecha de conexión del usuario.')),
                ('password', models.CharField(help_text='Contraseña hasheada del usuario.', max_length=128)),
            ],
            options={
                'verbose_name': 'Seguridad de Autenticación',
                'verbose_name_plural': 'Seguridad de Autenticaciones',
                'db_table': 'system_segurity_data"."auth_segurity',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(db_column='id_municipality', primary_key=True, serialize=False)),
                ('municipality', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'data_locations"."municipalities',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=100)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'system_segurity_data"."roles',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(db_column='id_state', primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'data_locations"."states',
            },
        ),
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('birthdate', models.DateField()),
                ('auth_security', models.OneToOneField(db_column='id_auth_fk', on_delete=django.db.models.deletion.PROTECT, related_name='user', to='users.authsecurity')),
            ],
            options={
                'verbose_name': 'Dato de Usuario',
                'verbose_name_plural': 'Datos de Usuarios',
                'db_table': 'system_data"."data_users',
            },
        ),
        migrations.CreateModel(
            name='DataProfile',
            fields=[
                ('id', models.BigAutoField(db_column='id_profile', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('img_profile_path', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('address', models.ForeignKey(blank=True, db_column='address_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.address')),
                ('user', models.OneToOneField(db_column='id_user_fk', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.datauser')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'system_data"."data_profiles',
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(db_column='id_parishes', primary_key=True, serialize=False)),
                ('parish', models.CharField(max_length=255)),
                ('municipality', models.ForeignKey(db_column='id_municipality_fk', on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='users.municipality')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'data_locations"."parishes',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='parish',
            field=models.ForeignKey(db_column='id_parish_fk', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='users.parish'),
        ),
        migrations.AddField(
            model_name='authsecurity',
            name='rol',
            field=models.ForeignKey(db_column='id_rol_fk', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='users.roles'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(db_column='id_state_fk', on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='users.state'),
        ),
    ]
